# Project: cms
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o Analytics_Promotion.o Announcement.o CompanyHierarchy.o EmployeeManagement.o EmpProjTrack.o JobReferrals.o PeerReviews.o
LINKOBJ  = main.o Analytics_Promotion.o Announcement.o CompanyHierarchy.o EmployeeManagement.o EmpProjTrack.o JobReferrals.o PeerReviews.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = cms.exe
CXXFLAGS = $(CXXINCS) -std=c++11 -g3 -g
CFLAGS   = $(INCS) -std=c++11 -g3 -g
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Analytics_Promotion.o: Analytics_Promotion.cpp
	$(CPP) -c Analytics_Promotion.cpp -o Analytics_Promotion.o $(CXXFLAGS)

Announcement.o: Announcement.cpp
	$(CPP) -c Announcement.cpp -o Announcement.o $(CXXFLAGS)

CompanyHierarchy.o: CompanyHierarchy.cpp
	$(CPP) -c CompanyHierarchy.cpp -o CompanyHierarchy.o $(CXXFLAGS)

EmployeeManagement.o: EmployeeManagement.cpp
	$(CPP) -c EmployeeManagement.cpp -o EmployeeManagement.o $(CXXFLAGS)

EmpProjTrack.o: EmpProjTrack.cpp
	$(CPP) -c EmpProjTrack.cpp -o EmpProjTrack.o $(CXXFLAGS)

JobReferrals.o: JobReferrals.cpp
	$(CPP) -c JobReferrals.cpp -o JobReferrals.o $(CXXFLAGS)

PeerReviews.o: PeerReviews.cpp
	$(CPP) -c PeerReviews.cpp -o PeerReviews.o $(CXXFLAGS)
